"""Fix libfontconfig done

Revision ID: 210029436021
Revises: 444fa93afda8
Create Date: 2025-07-05 15:18:50.976833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '210029436021'
down_revision = '444fa93afda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=100), nullable=False))
        batch_op.drop_column('html_template')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_template', mysql.TEXT(), nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
