"""adjust existing template table

Revision ID: 444fa93afda8
Revises: da1f3a7e0977
Create Date: 2025-07-03 15:36:56.432592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444fa93afda8'
down_revision = 'da1f3a7e0977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'template', ['template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
