"""Initial migration

Revision ID: 556b9df655f3
Revises: 
Create Date: 2025-06-14 22:49:57.234779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '556b9df655f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.drop_column('proyek')
        batch_op.drop_column('pendidikan')
        batch_op.drop_column('pengalaman')
        batch_op.drop_column('skill')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('pengalaman', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('pendidikan', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('proyek', mysql.TEXT(), nullable=True))
        batch_op.drop_column('skills')
        batch_op.drop_column('education')
        batch_op.drop_column('experience')
        batch_op.drop_column('summary')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
