"""update model CV: add Leadership, Activity, Language, Interest, update Education & CV

Revision ID: 7309f0ca4feb
Revises: c409dcc78dad
Create Date: 2025-07-05 17:09:59.235660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7309f0ca4feb'
down_revision = 'c409dcc78dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('proficiency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leadership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('sim')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('nationality')
        batch_op.drop_column('birth_place')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('address')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpa', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('gpa')

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('gender', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('birth_place', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('nationality', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('marital_status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sim', mysql.VARCHAR(length=50), nullable=True))

    op.drop_table('leadership')
    op.drop_table('language')
    op.drop_table('interest')
    op.drop_table('activity')
    # ### end Alembic commands ###
