"""add skill model

Revision ID: c409dcc78dad
Revises: 210029436021
Create Date: 2025-07-05 16:59:56.127421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c409dcc78dad'
down_revision = '210029436021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_column('html_template')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_template', mysql.TEXT(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    op.drop_table('skill')
    # ### end Alembic commands ###
