"""update table CV dan Education

Revision ID: da1f3a7e0977
Revises: fcb2966912b3
Create Date: 2025-06-22 18:30:04.969067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da1f3a7e0977'
down_revision = 'fcb2966912b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('school_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('major', sa.String(length=100), nullable=True))
        batch_op.drop_column('school')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('major')
        batch_op.drop_column('school_name')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
