"""Add education and experience models

Revision ID: fcb2966912b3
Revises: 556b9df655f3
Create Date: 2025-06-16 23:14:38.662936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcb2966912b3'
down_revision = '556b9df655f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('birth_place', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sim', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_description', sa.Text(), nullable=True))
        batch_op.drop_column('education')
        batch_op.drop_column('summary')
        batch_op.drop_column('title')
        batch_op.drop_column('skills')
        batch_op.drop_column('experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('skills', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('summary', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('education', mysql.TEXT(), nullable=True))
        batch_op.drop_column('profile_description')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('sim')
        batch_op.drop_column('marital_status')
        batch_op.drop_column('nationality')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_place')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('experience')
    op.drop_table('education')
    # ### end Alembic commands ###
